services:
  mysql:
    image: mysql:8.4@sha256:d36d39a64cd12a5c1cc9e6aa2bfb5f8d4c81a2f6586e0a04a9ae13939db02209
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fk_todos
    ports:
      - 3306:3306
    volumes:
      - mysql-data2:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64 # 使用時の環境によって適宜変更する必要がある。
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql-data2:
