services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fk_todos
    ports:
      - 3306:3306
    volumes:
      - mysql-data2:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64 # 使用時の環境によって適宜変更する必要がある。
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql-data2:
